[project]
name = "repl-nix-excelmetaextractor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.58.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "streamlit>=1.41.1",
    "matplotlib>=3.8.2",
]
